spring.application.name=multitenancy

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Tenants (custom properties) ---
tenants.tenant1.jdbc-url=jdbc:postgresql://localhost:5432/tenant_db1
tenants.tenant1.username=tenant1_user
tenants.tenant1.password=tenant1_pass

tenants.tenant2.jdbc-url=jdbc:postgresql://localhost:5432/tenant_db2
tenants.tenant2.username=tenant2_user
tenants.tenant2.password=tenant2_pass

# --- Server ---
server.port=8080
